--- TO BE EXECUTED AS ADMIN USER ---


CREATE USER user_admin PASSWORD='Summer07' DEFAULT_ROLE = USERADMIN  DEFAULT_SECONDARY_ROLES = ('ALL') MUST_CHANGE_PASSWORD = false;
GRANT ROLE USERADMIN TO USER user_admin;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE USERADMIN;

CREATE USER mstr_user PASSWORD='Summer07' DEFAULT_ROLE = SYSADMIN  DEFAULT_SECONDARY_ROLES = ('ALL') MUST_CHANGE_PASSWORD = false;
GRANT ROLE SYSADMIN TO USER mstr_user;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;


CREATE ROLE MSTR_ROLE;
GRANT ROLE MSTR_ROLE TO ROLE SYSADMIN;
GRANT ROLE MSTR_ROLE TO USER MSTR_USER;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE MSTR_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE MSTR_ROLE;
