select YEAR_QUARTER_NBR, count(*) 
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY
group by 1 order by 1 desc;

select a.AIRLINE_OAI_CODE
     , max(a.AIRLINE_NAME) as AIRLINE_NAME
     , h.AIRPORT_OAI_CODE
     , max(h.AIRPORT_DISPLAY_NAME) as AIRPORT_DISPLAY_NAME
     , min(i.YEAR_QUARTER_NBR) as min_yr_qtr
     , max(i.YEAR_QUARTER_NBR) as max_yr_qtr
     , sum(i.PASSENGER_QTY) as PASSENGER_QTY
     , count(*) 
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS'
group by a.AIRLINE_OAI_CODE, h.AIRPORT_OAI_CODE order by 7 desc;


SELECT ((i.ITINERARY_OAI_ID*10)+0)::bigint as ITINERARY_OAI_ID
     , i.ITINERARY_OAI_ID as original_itin_oai_id
     , i.YEAR_QUARTER_NBR, i.YEAR_QUARTER_START_DATE
     , i.REPORTING_AIRLINE_ENTITY_ID, i.REPORTING_AIRLINE_ENTITY_KEY
     , i.DEPART_AIRPORT_HISTORY_ID, i.DEPART_AIRPORT_HISTORY_KEY
     , i.ROUND_TRIP_FARE_IND, i.ONLINE_PURCHASE_IND
     , i.BULK_FARE_IND, i.FARE_CREDIBILITY_IND, i.DISTANCE_GROUP_OAI_ID, i.GEOGRAPHIC_TYPE_OAI_ID
     , i.COUPON_QTY, i.PASSENGER_QTY, i.DISTANCE_SMI, i.FLOWN_DISTANCE_SMI
     , (i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::integer as FARE_PER_PERSON_USD
     , ((i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::float / i.DISTANCE_SMI)::numeric(7,5) as FARE_PER_MILE_USD
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK'
union
SELECT ((i.ITINERARY_OAI_ID*10)+1)::bigint as ITINERARY_OAI_ID
     , i.ITINERARY_OAI_ID as original_itin_oai_id
     , i.YEAR_QUARTER_NBR, i.YEAR_QUARTER_START_DATE
     , i.REPORTING_AIRLINE_ENTITY_ID, i.REPORTING_AIRLINE_ENTITY_KEY
     , i.DEPART_AIRPORT_HISTORY_ID, i.DEPART_AIRPORT_HISTORY_KEY
     , i.ROUND_TRIP_FARE_IND, i.ONLINE_PURCHASE_IND
     , i.BULK_FARE_IND, i.FARE_CREDIBILITY_IND, i.DISTANCE_GROUP_OAI_ID, i.GEOGRAPHIC_TYPE_OAI_ID
     , i.COUPON_QTY, i.PASSENGER_QTY, i.DISTANCE_SMI, i.FLOWN_DISTANCE_SMI
     , (i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::integer as FARE_PER_PERSON_USD
     , ((i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::float / i.DISTANCE_SMI)::numeric(7,5) as FARE_PER_MILE_USD
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK'
union
SELECT ((i.ITINERARY_OAI_ID*10)+2)::bigint as ITINERARY_OAI_ID
     , i.ITINERARY_OAI_ID as original_itin_oai_id
     , i.YEAR_QUARTER_NBR, i.YEAR_QUARTER_START_DATE
     , i.REPORTING_AIRLINE_ENTITY_ID, i.REPORTING_AIRLINE_ENTITY_KEY
     , i.DEPART_AIRPORT_HISTORY_ID, i.DEPART_AIRPORT_HISTORY_KEY
     , i.ROUND_TRIP_FARE_IND, i.ONLINE_PURCHASE_IND
     , i.BULK_FARE_IND, i.FARE_CREDIBILITY_IND, i.DISTANCE_GROUP_OAI_ID, i.GEOGRAPHIC_TYPE_OAI_ID
     , i.COUPON_QTY, i.PASSENGER_QTY, i.DISTANCE_SMI, i.FLOWN_DISTANCE_SMI
     , (i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::integer as FARE_PER_PERSON_USD
     , ((i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::float / i.DISTANCE_SMI)::numeric(7,5) as FARE_PER_MILE_USD
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK'
union
SELECT ((i.ITINERARY_OAI_ID*10)+3)::bigint as ITINERARY_OAI_ID
     , i.ITINERARY_OAI_ID as original_itin_oai_id
     , i.YEAR_QUARTER_NBR, i.YEAR_QUARTER_START_DATE
     , i.REPORTING_AIRLINE_ENTITY_ID, i.REPORTING_AIRLINE_ENTITY_KEY
     , i.DEPART_AIRPORT_HISTORY_ID, i.DEPART_AIRPORT_HISTORY_KEY
     , i.ROUND_TRIP_FARE_IND, i.ONLINE_PURCHASE_IND
     , i.BULK_FARE_IND, i.FARE_CREDIBILITY_IND, i.DISTANCE_GROUP_OAI_ID, i.GEOGRAPHIC_TYPE_OAI_ID
     , i.COUPON_QTY, i.PASSENGER_QTY, i.DISTANCE_SMI, i.FLOWN_DISTANCE_SMI
     , (i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::integer as FARE_PER_PERSON_USD
     , ((i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::float / i.DISTANCE_SMI)::numeric(7,5) as FARE_PER_MILE_USD
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK'
union
SELECT ((i.ITINERARY_OAI_ID*10)+4)::bigint as ITINERARY_OAI_ID
     , i.ITINERARY_OAI_ID as original_itin_oai_id
     , i.YEAR_QUARTER_NBR, i.YEAR_QUARTER_START_DATE
     , i.REPORTING_AIRLINE_ENTITY_ID, i.REPORTING_AIRLINE_ENTITY_KEY
     , i.DEPART_AIRPORT_HISTORY_ID, i.DEPART_AIRPORT_HISTORY_KEY
     , i.ROUND_TRIP_FARE_IND, i.ONLINE_PURCHASE_IND
     , i.BULK_FARE_IND, i.FARE_CREDIBILITY_IND, i.DISTANCE_GROUP_OAI_ID, i.GEOGRAPHIC_TYPE_OAI_ID
     , i.COUPON_QTY, i.PASSENGER_QTY, i.DISTANCE_SMI, i.FLOWN_DISTANCE_SMI
     , (i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::integer as FARE_PER_PERSON_USD
     , ((i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::float / i.DISTANCE_SMI)::numeric(7,5) as FARE_PER_MILE_USD
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK'
union
SELECT ((i.ITINERARY_OAI_ID*10)+5)::bigint as ITINERARY_OAI_ID
     , i.ITINERARY_OAI_ID as original_itin_oai_id
     , i.YEAR_QUARTER_NBR, i.YEAR_QUARTER_START_DATE
     , i.REPORTING_AIRLINE_ENTITY_ID, i.REPORTING_AIRLINE_ENTITY_KEY
     , i.DEPART_AIRPORT_HISTORY_ID, i.DEPART_AIRPORT_HISTORY_KEY
     , i.ROUND_TRIP_FARE_IND, i.ONLINE_PURCHASE_IND
     , i.BULK_FARE_IND, i.FARE_CREDIBILITY_IND, i.DISTANCE_GROUP_OAI_ID, i.GEOGRAPHIC_TYPE_OAI_ID
     , i.COUPON_QTY, i.PASSENGER_QTY, i.DISTANCE_SMI, i.FLOWN_DISTANCE_SMI
     , (i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::integer as FARE_PER_PERSON_USD
     , ((i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::float / i.DISTANCE_SMI)::numeric(7,5) as FARE_PER_MILE_USD
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK'
union
SELECT ((i.ITINERARY_OAI_ID*10)+6)::bigint as ITINERARY_OAI_ID
     , i.ITINERARY_OAI_ID as original_itin_oai_id
     , i.YEAR_QUARTER_NBR, i.YEAR_QUARTER_START_DATE
     , i.REPORTING_AIRLINE_ENTITY_ID, i.REPORTING_AIRLINE_ENTITY_KEY
     , i.DEPART_AIRPORT_HISTORY_ID, i.DEPART_AIRPORT_HISTORY_KEY
     , i.ROUND_TRIP_FARE_IND, i.ONLINE_PURCHASE_IND
     , i.BULK_FARE_IND, i.FARE_CREDIBILITY_IND, i.DISTANCE_GROUP_OAI_ID, i.GEOGRAPHIC_TYPE_OAI_ID
     , i.COUPON_QTY, i.PASSENGER_QTY, i.DISTANCE_SMI, i.FLOWN_DISTANCE_SMI
     , (i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::integer as FARE_PER_PERSON_USD
     , ((i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::float / i.DISTANCE_SMI)::numeric(7,5) as FARE_PER_MILE_USD
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK'
union
SELECT ((i.ITINERARY_OAI_ID*10)+7)::bigint as ITINERARY_OAI_ID
     , i.ITINERARY_OAI_ID as original_itin_oai_id
     , i.YEAR_QUARTER_NBR, i.YEAR_QUARTER_START_DATE
     , i.REPORTING_AIRLINE_ENTITY_ID, i.REPORTING_AIRLINE_ENTITY_KEY
     , i.DEPART_AIRPORT_HISTORY_ID, i.DEPART_AIRPORT_HISTORY_KEY
     , i.ROUND_TRIP_FARE_IND, i.ONLINE_PURCHASE_IND
     , i.BULK_FARE_IND, i.FARE_CREDIBILITY_IND, i.DISTANCE_GROUP_OAI_ID, i.GEOGRAPHIC_TYPE_OAI_ID
     , i.COUPON_QTY, i.PASSENGER_QTY, i.DISTANCE_SMI, i.FLOWN_DISTANCE_SMI
     , (i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::integer as FARE_PER_PERSON_USD
     , ((i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::float / i.DISTANCE_SMI)::numeric(7,5) as FARE_PER_MILE_USD
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK'
union
SELECT ((i.ITINERARY_OAI_ID*10)+8)::bigint as ITINERARY_OAI_ID
     , i.ITINERARY_OAI_ID as original_itin_oai_id
     , i.YEAR_QUARTER_NBR, i.YEAR_QUARTER_START_DATE
     , i.REPORTING_AIRLINE_ENTITY_ID, i.REPORTING_AIRLINE_ENTITY_KEY
     , i.DEPART_AIRPORT_HISTORY_ID, i.DEPART_AIRPORT_HISTORY_KEY
     , i.ROUND_TRIP_FARE_IND, i.ONLINE_PURCHASE_IND
     , i.BULK_FARE_IND, i.FARE_CREDIBILITY_IND, i.DISTANCE_GROUP_OAI_ID, i.GEOGRAPHIC_TYPE_OAI_ID
     , i.COUPON_QTY, i.PASSENGER_QTY, i.DISTANCE_SMI, i.FLOWN_DISTANCE_SMI
     , (i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::integer as FARE_PER_PERSON_USD
     , ((i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::float / i.DISTANCE_SMI)::numeric(7,5) as FARE_PER_MILE_USD
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK'
union
SELECT ((i.ITINERARY_OAI_ID*10)+9)::bigint as ITINERARY_OAI_ID
     , i.ITINERARY_OAI_ID as original_itin_oai_id
     , i.YEAR_QUARTER_NBR, i.YEAR_QUARTER_START_DATE
     , i.REPORTING_AIRLINE_ENTITY_ID, i.REPORTING_AIRLINE_ENTITY_KEY
     , i.DEPART_AIRPORT_HISTORY_ID, i.DEPART_AIRPORT_HISTORY_KEY
     , i.ROUND_TRIP_FARE_IND, i.ONLINE_PURCHASE_IND
     , i.BULK_FARE_IND, i.FARE_CREDIBILITY_IND, i.DISTANCE_GROUP_OAI_ID, i.GEOGRAPHIC_TYPE_OAI_ID
     , i.COUPON_QTY, i.PASSENGER_QTY, i.DISTANCE_SMI, i.FLOWN_DISTANCE_SMI
     , (i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::integer as FARE_PER_PERSON_USD
     , ((i.FARE_PER_PERSON_USD * (1+(uniform(-0.1::float, 0.1::float, random()))))::float / i.DISTANCE_SMI)::numeric(7,5) as FARE_PER_MILE_USD
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
from AIR_OAI_FACTS.AIRFARE_SURVEY_ITINERARY i
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on i.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on i.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK'
order by 2,1,3
;

select FLIGHT_PASS_TYPE, count(*) from AIR_OAI.AIR_OAI_FACTS.AIRFARE_SURVEY_COUPON group by 1;
-- A/D/E ... 

SELECT ((c.ITINERARY_OAI_ID*10)+0)::bigint as ITINERARY_OAI_ID
     , c.ITINERARY_OAI_ID as original_itin_oai_id
     , FLIGHT_PASS_SEQ, YEAR_QUARTER_NBR, YEAR_QUARTER_START_DATE
     , ((c.MARKET_OAI_ID*10)+0)::bigint as MARKET_OAI_ID
     , c.MARKET_OAI_ID as original_market_oai_id
     , TICKETING_AIRLINE_ENTITY_ID, TICKETING_AIRLINE_ENTITY_KEY
     , OPERATING_AIRLINE_ENTITY_ID, OPERATING_AIRLINE_ENTITY_KEY
     , REPORTING_AIRLINE_ENTITY_ID, REPORTING_AIRLINE_ENTITY_KEY
     , DEPART_AIRPORT_HISTORY_ID, DEPART_AIRPORT_HISTORY_KEY, ARRIVE_AIRPORT_HISTORY_ID, ARRIVE_AIRPORT_HISTORY_KEY
     , TRIP_BREAK_CODE, GATEWAY_IND, DISTANCE_GROUP_OAI_ID, AIRFARE_CLASS_CODE
     , ITINERARY_GEOGRAPHIC_TYPE_OAI_ID, COUPON_GEOGRAPHIC_TYPE_OAI_ID
     , FLIGHT_PASS_TYPE, FLIGHT_PASS_QTY, PASSENGERS_QTY, DISTANCE_SMI
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
     , AIRFARE_SURVEY_COUPON_PK
FROM AIR_OAI.AIR_OAI_FACTS.AIRFARE_SURVEY_COUPON c
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on c.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on c.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK' 
union
SELECT ((c.ITINERARY_OAI_ID*10)+1)::bigint as ITINERARY_OAI_ID
     , c.ITINERARY_OAI_ID as original_itin_oai_id
     , FLIGHT_PASS_SEQ, YEAR_QUARTER_NBR, YEAR_QUARTER_START_DATE
     , ((c.MARKET_OAI_ID*10)+1)::bigint as MARKET_OAI_ID
     , c.MARKET_OAI_ID as original_market_oai_id
     , TICKETING_AIRLINE_ENTITY_ID, TICKETING_AIRLINE_ENTITY_KEY
     , OPERATING_AIRLINE_ENTITY_ID, OPERATING_AIRLINE_ENTITY_KEY
     , REPORTING_AIRLINE_ENTITY_ID, REPORTING_AIRLINE_ENTITY_KEY
     , DEPART_AIRPORT_HISTORY_ID, DEPART_AIRPORT_HISTORY_KEY, ARRIVE_AIRPORT_HISTORY_ID, ARRIVE_AIRPORT_HISTORY_KEY
     , TRIP_BREAK_CODE, GATEWAY_IND, DISTANCE_GROUP_OAI_ID, AIRFARE_CLASS_CODE
     , ITINERARY_GEOGRAPHIC_TYPE_OAI_ID, COUPON_GEOGRAPHIC_TYPE_OAI_ID
     , FLIGHT_PASS_TYPE, FLIGHT_PASS_QTY, PASSENGERS_QTY, DISTANCE_SMI
     , 1::byteint as expanded_row_ind, 'gxclark'::text as CREATED_BY, current_timestamp::timestamp(0) as CREATED_TMST
     , null::text as UPDATED_BY, null::timestamp(0) as UPDATED_TMST
     , AIRFARE_SURVEY_COUPON_PK
FROM AIR_OAI.AIR_OAI_FACTS.AIRFARE_SURVEY_COUPON c
join AIR_OAI_DIMS.AIRLINE_ENTITIES a on c.REPORTING_AIRLINE_ENTITY_ID = a.AIRLINE_ENTITY_ID
join AIR_OAI_DIMS.AIRPORT_HISTORY h on c.DEPART_AIRPORT_HISTORY_ID = h.AIRPORT_HISTORY_ID
where a.AIRLINE_OAI_CODE = 'AS' and h.AIRPORT_OAI_CODE = 'KWK' 
order by 1,2;


SELECT ITINERARY_OAI_ID -- magnify
    , MARKET_OAI_ID -- magnify
    , YEAR_QUARTER_NBR
    , YEAR_QUARTER_START_DATE
    , TICKETING_AIRLINE_ENTITY_ID
    , TICKETING_AIRLINE_ENTITY_KEY
    , TICKETING_AIRLINE_CHANGE_IND
    , TICKETING_AIRLINES_GROUP_CODE
    , OPERATING_AIRLINE_ENTITY_ID
    , OPERATING_AIRLINE_ENTITY_KEY
    , OPERATING_AIRLINE_CHANGE_IND
    , OPERATING_AIRLINES_GROUP_CODE
    , REPORTING_AIRLINE_ENTITY_ID
    , REPORTING_AIRLINE_ENTITY_KEY
    , DEPART_AIRPORT_HISTORY_ID
    , DEPART_AIRPORT_HISTORY_KEY
    , ARRIVE_AIRPORT_HISTORY_ID
    , ARRIVE_AIRPORT_HISTORY_KEY
    , AIRPORTS_GROUP_OAI_CODE
    , WORLD_AREAS_GROUP_OAI_CODE
    , ITINERARY_GEOGRAHIC_TYPE_OAI_ID
    , MARKET_GEOGRAHIC_TYPE_OAI_ID
    , MARKET_DISTANCE_GROUP_OAI_ID
    , BULK_FARE_IND
    , MARKET_COUPON_QTY
    , PASSENGER_QTY
    , MARKET_FARE_AMOUNT_USD -- > randomize ... 
    , MARKET_DISTANCE_SMI
    , MARKET_FLOWN_DISTANCE_SMI --- > maybe this is used to allocate fare to the market?
    , NON_STOP_DISTANCE_SMI
    , CREATED_BY
    , CREATED_TMST
    , UPDATED_BY
    , UPDATED_TSMT
FROM AVIATION.AIR_OAI_FACTS.AIRFARE_SURVEY_MARKET;





